export const counties = [
    "Baringo", "Bomet", "Bungoma", "Busia", "Elgeyo Marakwet", "Embu", "Garissa", "Homa Bay", "Isiolo", "Kajiado",
    "Kakamega", "Kericho", "Kiambu", "Kilifi", "Kirinyaga", "Kisii", "Kisumu", "Kitui", "Kwale", "Laikipia",
    "Lamu", "Machakos", "Makueni", "Mandera", "Meru", "Migori", "Mombasa", "Murang'a", "Nakuru", "Nandi",
    "Narok", "Nairobi", "Nyamira", "Nyandarua", "Nyeri", "Samburu", "Siaya", "Taita Taveta", "Tana River",
    "Tharaka Nithi", "Trans Nzoia", "Uasin Gishu", "Vihiga", "Wajir", "West Pokot", "Nairobi City",
  ];
  
  export const towns = {
    "Baringo": ["Kabarnet", "Eldama Ravine", "Marigat"],
    "Bomet": ["Bomet Town", "Mogogosiek", "Chepalungu"],
    "Bungoma": ["Bungoma Town", "Chwele", "Webuye", "Kimilili"],
    "Busia": ["Busia Town", "Bukhayo", "Port Victoria"],
    "Elgeyo Marakwet": ["Iten", "Kapcherop", "Kaben"],
    "Embu": ["Embu Town", "Mbeere", "Mukuuni"],
    "Garissa": ["Garissa Town", "Balambala", "Iftin"],
    "Homa Bay": ["Homa Bay Town", "Rachuonyo", "Mbita"],
    "Isiolo": ["Isiolo Town", "Garbatulla", "Merti"],
    "Kajiado": ["Kajiado Town", "Kitengela", "Ngong"],
    "Kakamega": ["Kakamega Town", "Lurambi", "Shinyalu"],
    "Kericho": ["Kericho Town", "Sotik", "Bomet"],
    "Kiambu": ["Kiambu Town", "Thika", "Ruiru", "Kimbo"],
    "Kilifi": ["Kilifi Town", "Malindi", "Vasco da Gama"],
    "Kirinyaga": ["Kerugoya", "Kutus", "Kianyaga"],
    "Kisii": ["Kisii Town", "Nyamira", "Masaba"],
    "Kisumu": ["Kisumu City", "Ahero", "Muhoroni"],
    "Kitui": ["Kitui Town", "Mutomo", "Kangundo"],
    "Kwale": ["Kwale Town", "Diani", "Ukunda"],
    "Laikipia": ["Nanyuki", "Nyahururu", "Rumuruti"],
    "Lamu": ["Lamu Town", "Shela", "Mpeketoni"],
    "Machakos": ["Machakos Town", "Mumbuni", "Kangundo"],
    "Makueni": ["Wote", "Makindu", "Mtito Andei"],
    "Mandera": ["Mandera Town", "Takaba", "Rhamu"],
    "Meru": ["Meru Town", "Nkubu", "Kianjai"],
    "Migori": ["Migori Town", "Rongo", "Kehancha"],
    "Mombasa": ["Mombasa City", "Likoni", "Nyali"],
    "Murang'a": ["Murang'a Town", "Kangema", "Kenol"],
    "Nakuru": ["Nakuru Town", "Naivasha", "Molo"],
    "Nandi": ["Kapsabet", "Nandi Hills", "Mosoriot"],
    "Narok": ["Narok Town", "Maasai Mara", "Nakuru"],
    "Nairobi": ["Nairobi City", "Westlands", "Gikambura"],
    "Nyamira": ["Nyamira Town", "Bokwa", "Binyenya"],
    "Nyandarua": ["Ol Kalou", "Kinangop", "Ndaragwa"],
    "Nyeri": ["Nyeri Town", "Kieni", "Othaya"],
    "Samburu": ["Maralal", "Wamba", "Baragoi"],
    "Siaya": ["Siaya Town", "Bondo", "Ugunja"],
    "Taita Taveta": ["Voi", "Taveta", "Mwatate"],
    "Tana River": ["Garissa", "Mpeketoni", "Bura"],
    "Tharaka Nithi": ["Chuka", "Maara", "Tharaka"],
    "Trans Nzoia": ["Kitale", "Kiminini", "Endebess"],
    "Uasin Gishu": ["Eldoret", "Ziwa", "Kesses"],
    "Vihiga": ["Vihiga Town", "Sabatia", "Luanda"],
    "Wajir": ["Wajir Town", "Bute", "Griftu"],
    "West Pokot": ["Kapenguria", "Sigor", "Lelan"],
    "Nairobi City": ["Nairobi City", "Westlands", "Kilimani"],
  };
  